# Change these first
owner: duruapp # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

assignees: 
  - bennimmo

sites:
  - name: Duru App Hosting
    url: https://go.duru.app
    icon: https://raw.githubusercontent.com/duruapp/upptime/master/assets/app.png
  - name: Duru API
    url: https://duru-backend-wut4zsxq6q-nw.a.run.app/status
    icon: https://raw.githubusercontent.com/duruapp/upptime/master/assets/api.png
  - name: Duru Databases
    url: https://duru-backend-wut4zsxq6q-nw.a.run.app/status/database
    icon: https://raw.githubusercontent.com/duruapp/upptime/master/assets/database.png
  - name: Duru Realtime Databases
    url: https://duru-backend-wut4zsxq6q-nw.a.run.app/status/realtime_database
    icon: https://raw.githubusercontent.com/duruapp/upptime/master/assets/data-processing.png
  - name: Duru Telephony Services
    url: https://duru-backend-wut4zsxq6q-nw.a.run.app/status/telephony
    icon: https://raw.githubusercontent.com/duruapp/upptime/master/assets/telephone.png
  - name: Duru AI Services
    url: https://duru-backend-wut4zsxq6q-nw.a.run.app/status/ai
    icon: https://raw.githubusercontent.com/duruapp/upptime/master/assets/ai.png
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.duru.app
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Duru Uptime
  introTitle: "**Duru** Uptime monitoring"
  introMessage: Please get in touch with support@duru.app to resolve any problems.
  navbar:
    - title: Status
      href: /
    - title: Duru Login
      href: https://go.duru.app

i18n:
  footer: Duru Tech Ltd

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
